# Generated by Django 6.1 on 2026-10-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_alter_task_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="slug",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
