# Generated by Django 6.1 on 2026-10-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_backfill_project_slugs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
