# Generated by Django 6.1 on 2026-10-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_alter_project_slug"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["todo", "in_progress", "done"])),
                name="task_status_valid",
            ),
        ),
    ]
